MNO_DEVPL_HOST: https://dev-platform.maestrano.io
MNO_DEVPL_API_PATH: /api/config/v1/marketplaces
MNO_DEVPL_ENV_NAME: demoapp-rails
MNO_DEVPL_ENV_KEY: df3773b5-0223-4a9e-99d0-8283922e06ce
MNO_DEVPL_ENV_SECRET: x-7p70puMPUQKcuL5R5XHw
